apiVersion: v2
appVersion: 0.2.4
description: A Helm chart for Kube-Home
name: kube-home
version: 0.1.1
home: https://github.com/EikenDram/kube-charts
sources:
- https://github.com/EikenDram/kube-charts
maintainers:
  - name: aiken
    email: eikendram@gmail.com