apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubehome.fullname" $ }}-app-config
  labels:
    app.kubernetes.io/component	: homepage
    {{- include "kubehome.labels" . | nindent 4 }}
data:
  locale.json: |
{{ .Values.config.locale | indent 4 }}